### PR TITLE
update kotlinx-serialization

### PR DESCRIPTION
**Pull request by vaudevillen**
update kotlinx-serialization

### CODE REVIEW

**Comment by asarazan** [comment]
Should we consider renaming this artifact to `bismarck-serialization-kotlinx-json` or something

**Comment by asarazan** [comment]
We could also prob just shorten it to `bismack-kotlinx-json`

**Comment by vaudevillen** [comment]
ah... yeah, i dig json

**Comment by asarazan** [comment]
Cool, I think you just need to update the folder name and then update your gradle.properties inside the module

**Comment by vaudevillen** [comment]
okay, renamed the module. fyi, the sample app doesn't work. i didn't want to fix it now... the error i was getting was weird. but i tested the artifact in volley-fm, and it works

**Pull request merged**
